/* =====================================================================
   DB_APPCOMERCIAL - PART 2: CREATE TABLES
   Version: 2.0
   Date: December 10, 2025
   
   Execute AFTER: 01_create_database.sql
   ===================================================================== */

USE DB_APPCOMERCIAL;
GO

PRINT '=== Creating Tables ===';
GO

-- ---------------------------------------------------------------------
-- Table: TM_PERFIL (User Roles)
-- ---------------------------------------------------------------------
CREATE TABLE TM_PERFIL (
    IDPERFIL            INT IDENTITY(1,1) PRIMARY KEY,
    NOMBREPERFIL        NVARCHAR(64) NOT NULL,
    DESCRIPCION         NVARCHAR(256) NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL
);
GO
PRINT '  Created: TM_PERFIL';
GO

-- ---------------------------------------------------------------------
-- Table: TM_USUARIO (Users)
-- ---------------------------------------------------------------------
CREATE TABLE TM_USUARIO (
    IDUSUARIO           INT IDENTITY(1,1) PRIMARY KEY,
    IDPERFIL            INT NOT NULL,
    LOGINUSUARIO        NVARCHAR(64) NOT NULL UNIQUE,
    CLAVE               NVARCHAR(256) NOT NULL,
    NOMBRES             NVARCHAR(128) NOT NULL,
    APELLIDOPATERNO     NVARCHAR(64) NOT NULL,
    APELLIDOMATERNO     NVARCHAR(64) NULL,
    EMAIL               NVARCHAR(128) NULL,
    TELEFONO            NVARCHAR(20) NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    IDSUPERVISOR        INT NULL,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL,
    CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (IDPERFIL) REFERENCES TM_PERFIL(IDPERFIL),
    CONSTRAINT FK_USUARIO_SUPERVISOR FOREIGN KEY (IDSUPERVISOR) REFERENCES TM_USUARIO(IDUSUARIO)
);
GO
PRINT '  Created: TM_USUARIO';
GO

-- ---------------------------------------------------------------------
-- Table: TM_EMPRESA (Companies/Clients)
-- ---------------------------------------------------------------------
CREATE TABLE TM_EMPRESA (
    IDEMPRESA           INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRECOMERCIAL     NVARCHAR(256) NOT NULL,
    RAZONSOCIAL         NVARCHAR(256) NULL,
    RUC                 NVARCHAR(11) NULL,
    SEDEPRINCIPAL       NVARCHAR(256) NULL,
    DOMICILIO           NVARCHAR(512) NULL,
    CONTACTO_NOMBRE     NVARCHAR(128) NULL,
    CONTACTO_EMAIL      NVARCHAR(128) NULL,
    CONTACTO_TELEFONO   NVARCHAR(20) NULL,
    CONTACTO_CARGO      NVARCHAR(64) NULL,
    TIPOCLIENTE         NVARCHAR(64) NULL,
    LINEANEGOCIO        NVARCHAR(128) NULL,
    SUBLINEANEGOCIO     NVARCHAR(128) NULL,
    TIPOCREDITO         NVARCHAR(64) NULL,
    TIPOCARTERA         NVARCHAR(64) NULL,
    ACTIVIDADECONOMICA  NVARCHAR(256) NULL,
    RIESGO              NVARCHAR(32) NULL,
    NUMTRABAJADORES     INT NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL
);
GO
PRINT '  Created: TM_EMPRESA';
GO

-- ---------------------------------------------------------------------
-- Table: TM_EMPRESA_SEDE (Company Locations/Branches)
-- ---------------------------------------------------------------------
CREATE TABLE TM_EMPRESA_SEDE (
    IDSEDE              INT IDENTITY(1,1) PRIMARY KEY,
    IDEMPRESA           INT NOT NULL,
    NOMBRESEDE          NVARCHAR(128) NOT NULL,
    DOMICILIO           NVARCHAR(512) NULL,
    TELEFONO            NVARCHAR(20) NULL,
    CONTACTO_NOMBRE     NVARCHAR(128) NULL,
    CONTACTO_EMAIL      NVARCHAR(128) NULL,
    CONTACTO_TELEFONO   NVARCHAR(20) NULL,
    ESPRINCIPAL         BIT NOT NULL DEFAULT 0,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL,
    CONSTRAINT FK_SEDE_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES TM_EMPRESA(IDEMPRESA) ON DELETE CASCADE
);
GO
PRINT '  Created: TM_EMPRESA_SEDE';
GO

-- ---------------------------------------------------------------------
-- Table: TM_SEGUIMIENTO_TIPO (Follow-up Types)
-- ---------------------------------------------------------------------
CREATE TABLE TM_SEGUIMIENTO_TIPO (
    IDTIPOSEGUIMIENTO   INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE              NVARCHAR(64) NOT NULL,
    DESCRIPCION         NVARCHAR(256) NULL,
    COLOR               NVARCHAR(7) NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE()
);
GO
PRINT '  Created: TM_SEGUIMIENTO_TIPO';
GO

-- ---------------------------------------------------------------------
-- Table: TM_SEGUIMIENTO (Follow-ups/Tasks)
-- ---------------------------------------------------------------------
CREATE TABLE TM_SEGUIMIENTO (
    IDSEGUIMIENTO       INT IDENTITY(1,1) PRIMARY KEY,
    IDEMPRESA           INT NOT NULL,
    IDTIPOSEGUIMIENTO   INT NULL,
    IDUSUARIOASIGNADO   INT NOT NULL,
    FECHAPROGRAMADA     DATE NOT NULL,
    HORAPROGRAMADA      TIME NULL,
    PRIORIDAD           NVARCHAR(16) NOT NULL DEFAULT 'MEDIA',
    ESTADO              NVARCHAR(32) NOT NULL DEFAULT 'PENDIENTE',
    NOTAS               NVARCHAR(1024) NULL,
    FECHACOMPLETADO     DATETIME NULL,
    RESULTADO           NVARCHAR(64) NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL,
    CONSTRAINT FK_SEGUIMIENTO_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES TM_EMPRESA(IDEMPRESA),
    CONSTRAINT FK_SEGUIMIENTO_TIPO FOREIGN KEY (IDTIPOSEGUIMIENTO) REFERENCES TM_SEGUIMIENTO_TIPO(IDTIPOSEGUIMIENTO),
    CONSTRAINT FK_SEGUIMIENTO_USUARIO FOREIGN KEY (IDUSUARIOASIGNADO) REFERENCES TM_USUARIO(IDUSUARIO),
    CONSTRAINT CHK_SEGUIMIENTO_PRIORIDAD CHECK (PRIORIDAD IN ('ALTA', 'MEDIA', 'BAJA')),
    CONSTRAINT CHK_SEGUIMIENTO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'EN_PROGRESO', 'COMPLETADO', 'CANCELADO'))
);
GO
PRINT '  Created: TM_SEGUIMIENTO';
GO

-- ---------------------------------------------------------------------
-- Table: TM_SEGUIMIENTO_DETALLE (Follow-up Details)
-- ---------------------------------------------------------------------
CREATE TABLE TM_SEGUIMIENTO_DETALLE (
    IDDETALLE           INT IDENTITY(1,1) PRIMARY KEY,
    IDSEGUIMIENTO       INT NOT NULL,
    TIPOCOMUNICACION    NVARCHAR(64) NULL,
    FECHA1ERCONTACTO    DATE NULL,
    ESTATUSCLIENTE      NVARCHAR(64) NULL,
    DETALLEESTATUS      NVARCHAR(512) NULL,
    TIPOLLAMADA         NVARCHAR(64) NULL,
    PRESUPUESTO         DECIMAL(18,2) NULL,
    OBSERVACIONES       NVARCHAR(1024) NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL,
    CONSTRAINT FK_DETALLE_SEGUIMIENTO FOREIGN KEY (IDSEGUIMIENTO) REFERENCES TM_SEGUIMIENTO(IDSEGUIMIENTO) ON DELETE CASCADE
);
GO
PRINT '  Created: TM_SEGUIMIENTO_DETALLE';
GO

-- ---------------------------------------------------------------------
-- Table: TM_INTERACCION (Interaction History)
-- ---------------------------------------------------------------------
CREATE TABLE TM_INTERACCION (
    IDINTERACCION       INT IDENTITY(1,1) PRIMARY KEY,
    IDEMPRESA           INT NOT NULL,
    IDSEGUIMIENTO       INT NULL,
    IDUSUARIO           INT NOT NULL,
    FECHAINTERACCION    DATETIME NOT NULL DEFAULT GETDATE(),
    TIPOINTERACCION     NVARCHAR(64) NOT NULL,
    DESCRIPCION         NVARCHAR(1024) NULL,
    RESULTADO           NVARCHAR(64) NULL,
    DURACIONMINUTOS     INT NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_INTERACCION_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES TM_EMPRESA(IDEMPRESA),
    CONSTRAINT FK_INTERACCION_SEGUIMIENTO FOREIGN KEY (IDSEGUIMIENTO) REFERENCES TM_SEGUIMIENTO(IDSEGUIMIENTO),
    CONSTRAINT FK_INTERACCION_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES TM_USUARIO(IDUSUARIO)
);
GO
PRINT '  Created: TM_INTERACCION';
GO

-- ---------------------------------------------------------------------
-- Table: TM_VENTA (Sales)
-- ---------------------------------------------------------------------
CREATE TABLE TM_VENTA (
    IDVENTA             INT IDENTITY(1,1) PRIMARY KEY,
    IDEMPRESA           INT NOT NULL,
    IDSEGUIMIENTO       INT NULL,
    IDUSUARIO           INT NOT NULL,
    FECHAVENTA          DATE NOT NULL,
    MONTO               DECIMAL(18,2) NOT NULL,
    MONEDA              NVARCHAR(3) NOT NULL DEFAULT 'PEN',
    DESCRIPCION         NVARCHAR(512) NULL,
    PRODUCTO            NVARCHAR(256) NULL,
    ESTADO              NVARCHAR(32) NOT NULL DEFAULT 'CERRADA',
    ACTIVO              BIT NOT NULL DEFAULT 1,
    USUARIOCREA         INT NULL,
    FECHACREA           DATETIME NOT NULL DEFAULT GETDATE(),
    USUARIOMODIFICA     INT NULL,
    FECHAMODIFICA       DATETIME NULL,
    CONSTRAINT FK_VENTA_EMPRESA FOREIGN KEY (IDEMPRESA) REFERENCES TM_EMPRESA(IDEMPRESA),
    CONSTRAINT FK_VENTA_SEGUIMIENTO FOREIGN KEY (IDSEGUIMIENTO) REFERENCES TM_SEGUIMIENTO(IDSEGUIMIENTO),
    CONSTRAINT FK_VENTA_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES TM_USUARIO(IDUSUARIO)
);
GO
PRINT '  Created: TM_VENTA';
GO

-- ---------------------------------------------------------------------
-- Table: TM_NOTIFICACION (Notifications - HU007)
-- ---------------------------------------------------------------------
CREATE TABLE TM_NOTIFICACION (
    IDNOTIFICACION      INT IDENTITY(1,1) PRIMARY KEY,
    IDUSUARIO           INT NOT NULL,
    TITULO              NVARCHAR(200) NOT NULL,
    MENSAJE             NVARCHAR(500) NULL,
    TIPO                NVARCHAR(50) NOT NULL DEFAULT 'INFO',
    LEIDA               BIT NOT NULL DEFAULT 0,
    FECHACREACION       DATETIME NOT NULL DEFAULT GETDATE(),
    FECHALEIDA          DATETIME NULL,
    TIPOENTIDAD         NVARCHAR(50) NULL,
    IDREFERENCIAENTIDAD INT NULL,
    ACTIVO              BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_NOTIFICACION_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES TM_USUARIO(IDUSUARIO),
    CONSTRAINT CHK_NOTIFICACION_TIPO CHECK (TIPO IN ('INFO', 'ALERTA', 'URGENTE', 'RECORDATORIO'))
);
GO
PRINT '  Created: TM_NOTIFICACION';
GO

PRINT '';
PRINT 'All 10 tables created successfully.';
PRINT 'Now run: 03_create_indexes.sql';
GO
